language: cpp
compiler:
  - gcc
  
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make

os:
  - linux
  - osx
